'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''drpDBs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpDBs As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chk_api control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_api As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_csharp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_csharp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_All As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_prc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_prc As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_bc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_bc As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_dal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_dal As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chk_cnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_cnt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_AppConnectionString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AppConnectionString As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CSharpAppConnectionString control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CSharpAppConnectionString As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_ConStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ConStr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drp_targetTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_targetTable As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_ObjClassName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ObjClassName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_IUClassName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_IUClassName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CountClassName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CountClassName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_IUSprocName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_IUSprocName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SelectSprocName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SelectSprocName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CountSprocName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CountSprocName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Submit As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btn_Reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Reset As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''pnl_Results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Results As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ltl_CodeResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltl_CodeResults As Global.System.Web.UI.WebControls.Literal
End Class
